on:
  pull_request:
    branches:
    - main

jobs:
  contributors:
    runs-on: ubuntu-latest
    name: Contributor Compliance Checks
    steps:
      - uses: actions/checkout@v2
      - id: inspection
        uses: greenpau/contributor-compliance-action@v1.0.12
        with:
          cla_consent_required: true
          signed_off_required: true
          issue_required: true
          max_commits: 1
          cla_consent_path: assets/cla/consent.yaml
